dataset:
    preprocess: False
    data_dir: '/data/sguo/Processed/2018_11_01_kidney_slice/SMS_2018_1101_1906_1_BG_2018_1101_1906_1/image_tile_256-256_step_128-128'
    input_channels: [1]
    target_channels: [6]
    split_by_column: sample_num
    split_ratio:
        train: 0.7
        val: 0.15
        test: 0.15
    height: 256
    width: 256
verbose: 10
trainer:
    model_dir: '/models_kidney_confocal/tile256_step128_fltr16_256_lr1e-3_do0_MSE_chan1_6_global_norm_augmented'
    batch_size: 32
    max_epochs: 200
    patience: 30
    metrics: coeff_determination
    loss: mean_squared_error
    augmentations: True
    callbacks:
        EarlyStopping:
            mode: min
            monitor: val_loss
            patience: 30
            verbose: True
        ModelCheckpoint:
            mode: min
            monitor: val_loss
            save_best_only: True
            verbose: True
        TensorBoard:
            histogram_freq: 0
            verbose: True
    optimizer:
        lr: 0.001
        name: Adam
network:
    class: UNet2D
    num_filters_per_block: [16, 32, 64, 128, 256]
    num_convs_per_block: 2
    filter_size: 3
    batch_norm: True
    activation: relu
    pooling_type: average
    skip_merge_type: concat
    upsampling: bilinear
    dropout: 0
    residual: True
    height: 256
    width: 256
    num_input_channels: 1
    num_target_channels: 1
    data_format: 'channels_first'
    final_activation: linear
